//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Service.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal_ClienteSocio
    {
        public int Id { get; set; }
        public int ClienteId { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
    
        public virtual Deal_Cliente Deal_Cliente { get; set; }
    }
}
