//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Service.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deal_Cliente()
        {
            this.Deal_ClienteEmail = new HashSet<Deal_ClienteEmail>();
            this.Deal_ClienteEndereco = new HashSet<Deal_ClienteEndereco>();
            this.Deal_ClienteSocio = new HashSet<Deal_ClienteSocio>();
            this.Deal_ClienteTelefone = new HashSet<Deal_ClienteTelefone>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CNPJ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal_ClienteEmail> Deal_ClienteEmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal_ClienteEndereco> Deal_ClienteEndereco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal_ClienteSocio> Deal_ClienteSocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal_ClienteTelefone> Deal_ClienteTelefone { get; set; }
    }
}
