//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Service.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deal_Cliente> Deal_Cliente { get; set; }
        public virtual DbSet<Deal_ClienteEmail> Deal_ClienteEmail { get; set; }
        public virtual DbSet<Deal_ClienteEndereco> Deal_ClienteEndereco { get; set; }
        public virtual DbSet<Deal_ClienteSocio> Deal_ClienteSocio { get; set; }
        public virtual DbSet<Deal_ClienteTelefone> Deal_ClienteTelefone { get; set; }
    }
}
